language: python
addons:
  postgresql: "9.3"
services:
  - postgresql
install: "pip install -r requirements.txt"
before_script:
  - psql -c 'create database recipehub_service;' -U postgres
script: make test